cmake_minimum_required(VERSION 3.18)
project(network_file_sharing LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
find_library(CRYPT_LIBRARY crypt REQUIRED)
add_executable(nfs-server server.cpp)
target_link_libraries(nfs-server PRIVATE ${CRYPT_LIBRARY} pthread)
add_executable(nfs-client client.cpp)
